config/routes.rb
Rails.application.routes.draw do

  root 'users#homepage'
  devise_for :users
  
  resources :plans do
    resources :subscriptions, only: [:show, :create, :new], on: :member 
    resources :features, shallow: true
  end

  resources :features, only: [:show] do
    resources :usages, shallow: true 
  end

  resources :subscriptions, only: [:index] do
    get 'success', on: :collection
  end

  resources :usages, only: [:index]
  resources :transactions, only: [:index]
  
end
  

app/models/usage.rb
# frozen_string_literal: true

class Usage < ApplicationRecord
  belongs_to :user
  belongs_to :feature
  before_create :create_bill
  validates :usage_quantity, presence: true

  private

  def create_bill
    usages = Usage.where(user_id: user_id, feature_id: feature_id).sum(:usage_quantity)
    self.over_usage_bill = if usages.zero?
                             usage_quantity
                           else
                             usages + usage_quantity
                           end
  end
end

app/controllers/usages_controller.rb
# frozen_string_literal: true

class UsagesController < ApplicationController
  before_action :set_usage, only: %i[edit update]
  before_action :usage_update, only: %i[update]
  before_action :authorize_usage, only: %i[index edit update]

  def index
    @usages = Usage.includes(:user, :feature).all
  end

  def new
    feature = Feature.find(params[:feature_id])
    @usage = feature.usages.new
  end

  def create
    usage = current_user.usages.new(usage_params)
    if usage.save!
      redirect_to feature_path(usage.feature.id), notice: I18n.t('success.usage')
    else
      redirect_to new_feature_usage_path, notice: I18n.t('failure.usage')
    end
  end

  def edit; end

  def update
    if @usage.update!(usage_update)
      redirect_to usages_path, notice: I18n.t('success.usageupdate')
    else
      redirect_to edit_usage_path(@usage), notice: I18n.t('failure.usageupdate')
    end
  end

  private

  def authorize_usage
    authorize Usage
  end

  def usage_params
    params.require(:usage).permit(:feature_id, :usage_quantity)
  end

  def set_usage
    @usage = Usage.find(params[:id])
  end

  def usage_update
    params.require(:usage).permit(:usage_quantity)
  end
end

app/views/usages/edit.html.erb
<%= form_with model: @usage,method: :patch, local: true do |f| %>
  <%= f.number_field :usage_quantity %>
  <%= f.submit %>
<% end %>   

app/views/usages/index.html.erb
<h1>Usage Management</h1>
<% @usages.each do |usage| %>
  <table class="table">
    <thead>
      <tr>
        <th>Quantity Used :</th>
        <th>Bill For Qualtity </th>
        <th>Used At</th>
        <th>Buyer Name:</th>
        <th>Feature Name:</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= usage.usage_quantity %> </td>
        <td> <%= usage.over_usage_bill %></td>
        <td> <%= usage.created_at.to_date %></td>
        <td> <%= usage.user.name %></td>
        <td> <%= usage.feature.name%></td>
        <td> <%= link_to "Edit Usage Qualtity", edit_usage_path(usage.id) %></td>
      </tr>
    </tbody>
  </table>
 <%end%>

app/views/usages/new.html.erb
<h1>add usage<h1>
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with model: @usage , url: feature_usages_path do |form| %>
      <div class="field form-group">
      <% form.label :usage_quantity %><br />
      <%= form.number_field :usage_quantity,required: true, autofocus: true, min: 0,autocomplete: "name", class: "form-control", placeholder: "Usage Quantity" %>
      </div>
    <div class="actions">
      <%= form.submit "Add Usage", class: "btn btn-primary" %>
    </div>
      <%= form.hidden_field :feature_id  %>
  </div>
<% end %> 
</div>