config/routes.rb
Rails.application.routes.draw do

  root 'users#homepage'
  devise_for :users
  
  resources :plans do
    resources :subscriptions, only: [:show, :create, :new], on: :member 
    resources :features, shallow: true
  end

  resources :features, only: [:show] do
    resources :usages, shallow: true 
  end

  resources :subscriptions, only: [:index] do
    get 'success', on: :collection
  end

  resources :usages, only: [:index]
  resources :transactions, only: [:index]
  
end
  

app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  include CreatePrice

  has_many :features, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :transactions, dependent: :destroy
  belongs_to :user

  enum interval: { 'month, year': 0 }

  validates :name, :monthly_fee, presence: true
  validates :monthly_fee, numericality: { greater_than_or_equal_to: 0 }

  before_create :create_stripe_reference

  def create_stripe_reference
    response = Plan.price_reference(monthly_fee, name)
    self.stripe_price_id = response.id
  end
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

require 'stripe'
class PlansController < ApplicationController
  before_action :authorize_plan, only: %i[new create]
  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def show
    @plan = Plan.find(params[:id])
    @subscription = @plan.subscriptions.build
  end

  def create
    user = User.find(current_user.id)
    plan = user.plans.new(plan_param)
    if plan.save!
      redirect_to plan, notice: I18n.t('success.plan')
    else
      redirect_to new_plan_path, notice: I18n.t('failure.plan')
    end
  end

  private

  def authorize_plan
    authorize Plan
  end

  def plan_param
    params.require(:plan).permit(:name, :monthly_fee)
  end
end

app/helpers/plans_helper.rb
# frozen_string_literal: true

module PlansHelper
  def find_active_subscription(plan)
    if get_subscription = Subscription.find_by(user_id: current_user.id, plan_id: plan.id)
      Stripe::Subscription.retrieve(get_subscription&.stripe_id).status != 'active'
    else
      true
    end
  end
end

app/views/plans/index.html.erb
<h2>All Plans</h2>
<% @plans.each do |plan| %>
  <div class="panel panel-default">
    <div class="panel-heading">
        <strong>Plan Name : </strong>
        <%= plan.name %></h3>
        <br>
    </div>
    <div class="panel-heading">
        <strong>Monthly Fee: </strong>
        <%= number_to_currency(plan.monthly_fee) %>
        <br><br>
        <%= link_to "Show Plan", plan_path(plan), class: 'btn btn-primary' %>
        <% if find_active_subscription(plan) == false %>
          <%= link_to "Already Buyed", class: 'btn btn-primary'  %>
        <%end%>
    </div>
  </div>
<% end %>

app/views/plans/new.html.erb
<h1>Plan Creation </h1>
<div class="panel panel-default">
    <div class="panel-body">
      <%= form_with model: @plan, local: true do |form| %>
      <div class=" field form-group"> 
          <div class="field form-group">
          <% form.label :name %><br />
          <%= form.text_field :name, autofocus: true,required: true, autocomplete: "name", class: "form-control", placeholder: "Name" %>
      </div>
        <div class="field form-group">
          <% form.label :monthly_fee %><br />
          <%= form.number_field :monthly_fee, autofocus: true,required: true, min: 0, autocomplete: "name", class: "form-control", placeholder: "Monthly Fee" %>
        </div>
        <div class="actions">
          <%= form.submit "Create Plan", class: "btn btn-primary" %>
        </div>
  </div>
  <% end %> 
</div>

app/views/plans/show.html.erb
<h1>PLAN</h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Plan Name : </strong>
    <%= @plan.name %></h3>
    <br>
  </div>
  <div class="panel-heading">
    <strong>Monthly Fee: </strong>
    <%= number_to_currency(@plan.monthly_fee) %>
    <br/><br/>
    <% if current_user.role == "admin" %>
      <%= link_to "create features", new_plan_feature_path(@plan), class: 'btn btn-primary' %>
    <% end %>
    <br><br>
    <%= render @plan.features %>
    <% if current_user.role == "buyer" %>
      <% if find_active_subscription(@plan) %>
        <%= link_to "Buy Plan", plan_subscriptions_path(@plan , @subscription),class: 'btn btn-primary' ,method: :post %>
      <%end%>
    <%end%>
  </div>
</div>
    
    