config/routes.rb
Rails.application.routes.draw do

  root 'users#homepage'
  devise_for :users
  
  resources :plans do
    resources :subscriptions, only: [:show, :create, :new], on: :member 
    resources :features, shallow: true
  end

  resources :features, only: [:show] do
    resources :usages, shallow: true 
  end

  resources :subscriptions, only: [:index] do
    get 'success', on: :collection
  end

  resources :usages, only: [:index]
  resources :transactions, only: [:index]
  
end
  

app/models/feature.rb
# frozen_string_literal: true

class Feature < ApplicationRecord
  belongs_to :plan
  has_many :usages, dependent: :destroy
  has_many :users, through: :usages

  validates :name, :code, :max_unit_limit, :unit_price, presence: true
  validates :max_unit_limit, :unit_price, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/features_controller.rb
# frozen_string_literal: true

class FeaturesController < ApplicationController
  before_action :authorize_feature, only: %i[index new create]
  before_action :set_feature, only: %i[show]
  def index
    plan_id = params[:plan_id].to_i
    @features = Feature.where(plan_id: plan_id)
  end

  def new
    @feature = Feature.new
  end

  def show; end

  def create
    plan = Plan.find(params[:plan_id])
    @feature = plan.features.new(feature_param)
    if @feature.save!
      redirect_to plan_path(plan), notice: I18n.t('success.feature')
    else
      redirect_to new_plan_feature_path(plan), notice: I18n.t('failure.feature')
    end
  end

  private

  def authorize_feature
    authorize Feature
  end

  def feature_param
    params.require(:feature).permit(:name, :code, :unit_price, :max_unit_limit)
  end

  def set_feature
    @feature = Feature.find(params[:id])
  end
end

app/views/features/_feature.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <div class="panel-heading">
        <strong>Feature Name : </strong>
        <%= feature.name %></h3>
        <br>
      </div>
      <div class="panel-heading">
        <strong>Feature Code : </strong>
        <%= feature.code %></h3>
        <br>
      </div>
      <div class="panel-heading">
        <strong>Unit Prce : </strong>
        <%= feature.unit_price %></h3>
        <br>
      </div>
      <div class="panel-heading">
        <strong>Max Unit limit : </strong>
        <%= feature.max_unit_limit %></h3>
        <br>
      </div>
        <%if current_user.role == "buyer"%>
        <% unless find_active_subscription(feature.plan) %>
          <div class="panel-heading">
            <%= link_to "Use Feature", new_feature_usage_path(feature.id),class: 'btn btn-primary' %>
          </div>
          <div class="panel-heading">
            <%= link_to ' See Usage History' , feature_path(feature.id) ,class: 'btn btn-primary'%>
          </div>
        <%end%>
        <%end%>
    </div>
</div>

app/views/features/index.html.erb
<h1> ALL Features </h1>
<% @features.each do |feature| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-heading">
        <strong>Feature Name : </strong>
        <%= feature.name %></h3>
        <br>
      </div>  
    <div class="panel-heading">
      <strong>Feature Code : </strong>
      <%= feature.code %></h3>
      <br>
    </div>
    </div>
 </div>
<% end %>

app/views/features/new.html.erb
<h1>Feature Creation </h1>
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_with model: @feature , url: plan_features_path do |form| %>
      <div class="field form-group">
      <% form.label :name %><br />
      <%= form.text_field :name, autofocus: true,required: true, autocomplete: "name", class: "form-control", placeholder: "Name" %>
      </div>
    <div class="field form-group">
      <% form.label :code %><br />
      <%= form.text_field :code, autofocus: true,required: true, autocomplete: "name", class: "form-control", placeholder: "Code" %>
    </div>
    <div class="field form-group">
      <% form.label :unit_price %><br />
      <%= form.number_field :unit_price, autofocus: true,required: true,min: 0,autocomplete: "name", class: "form-control", placeholder: "Unit Price" %>
    </div>
    <div class="field form-group">
      <% form.label :max_unit_limit %><br />
      <%= form.number_field :max_unit_limit, autofocus: true, required: true,min: 0, autocomplete: "name", class: "form-control", placeholder: "Max Unit Limit" %>
    </div>
    <div class="actions">
      <%= form.submit "Create Feature", class: "btn btn-primary" %>
    </div>
  </div>
<% end %> 
</div>

app/views/features/show.html.erb
<h1>All Usages</h1>
<% @feature.usages.each do |usage| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-heading">
        <strong>Quantity Used  : </strong>
        <%= usage.usage_quantity %></h3>
        <br>
      </div>
    <div class="panel-heading">
      <strong>Over Usage Bill </strong>
      <%= usage.over_usage_bill %></h3>
      <br>
    </div>
    <div class="panel-heading">
      <strong>Used At </strong>
      <%= usage.created_at %></h3>
      <br>
    </div>
      <div class="panel-heading">
      <strong>Bill </strong>
      <%= usage.over_usage_bill %></h3>
      <br>
    </div>
    </div>
 </div>
 <%end%>